services:
  db:
    image: mongo:latest
    ports:
     - "27017:27017"
    container_name: db
    volumes: 
     - ~/mongo/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
