
ALTER TABLE LibraryDB.Books ADD COLUMN ISBN VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.ISBN") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN AccessionNo VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.AccessionNo") VIRTUAL, WITH VALIDATION;


ALTER TABLE LibraryDB.Books ADD COLUMN Title VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.Title") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN Edition VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.Edition") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN subtitle VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.subtitle") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN Author VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.Author") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN YearOfPublication VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.YearOfPublication") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN Publisher VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.Publisher") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN Pages INTEGER GENERATED ALWAYS AS (jsondata->>"$.Pages") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN Category VARCHAR(80) GENERATED ALWAYS AS (jsondata->>"$.Category") VIRTUAL, WITH VALIDATION;

ALTER TABLE LibraryDB.Books ADD COLUMN Price DECIMAL(7,2) GENERATED ALWAYS AS (jsondata->>"$.Price") VIRTUAL, WITH VALIDATION;